# ã‚µã‚¤ãƒˆã®åŸºæœ¬æƒ…å ±
site:
  tab: Frosti # ãƒ–ãƒ©ã‚¦ã‚¶ã®ã‚¿ãƒ–ã«è¡¨ç¤ºã•ã‚Œã‚‹ãƒ†ã‚­ã‚¹ãƒˆ
  title: ğŸ’  Frosti # ã‚µã‚¤ãƒˆã®ã‚¿ã‚¤ãƒˆãƒ«
  description: A clean, elegant, and fast static blog template! ğŸš€ Developed with Astro # ã‚µã‚¤ãƒˆã®èª¬æ˜ï¼ˆSEOãªã©ã«ä½¿ç”¨ï¼‰
  language: en # ã‚µã‚¤ãƒˆã®è¨€èªï¼ˆä¾‹ï¼š"en"ã¯è‹±èªï¼‰
  favicon: /favicon.ico # ã‚µã‚¤ãƒˆã®ã‚¢ã‚¤ã‚³ãƒ³ï¼ˆãƒ–ãƒ©ã‚¦ã‚¶ã®ã‚¿ãƒ–ãªã©ã«è¡¨ç¤ºï¼‰
  theme: # è©³ç´°ãªãƒ†ãƒ¼ãƒè¨­å®š https://daisyui.com/docs/themes/
    light: winter # ãƒ©ã‚¤ãƒˆãƒ†ãƒ¼ãƒ
    dark: dracula # ãƒ€ãƒ¼ã‚¯ãƒ†ãƒ¼ãƒ
    code: github-dark # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã®ãƒ†ãƒ¼ãƒ https://shiki.style/themes
  date_format: ddd MMM DD YYYY # æ—¥ä»˜ãƒ•ã‚©ãƒ¼ãƒãƒƒãƒˆï¼ˆã‚«ã‚¹ã‚¿ãƒã‚¤ã‚ºå¯èƒ½ï¼‰
  blog: # ãƒ–ãƒ­ã‚°é–¢é€£ã®è¨­å®š
    pageSize: 8 # 1ãƒšãƒ¼ã‚¸ã‚ãŸã‚Šã®è¨˜äº‹æ•°
  menu: # ãƒ¡ãƒ‹ãƒ¥ãƒ¼è¨­å®š
    - id: home # ãƒ¡ãƒ‹ãƒ¥ãƒ¼é …ç›®ã®ãƒ¦ãƒ‹ãƒ¼ã‚¯ID
      text: Home # ãƒ¡ãƒ‹ãƒ¥ãƒ¼é …ç›®ã®è¡¨ç¤ºãƒ†ã‚­ã‚¹ãƒˆ
      href: / # ãƒ¡ãƒ‹ãƒ¥ãƒ¼é …ç›®ã®ãƒªãƒ³ã‚¯å…ˆ
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: About
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: Blogs
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: All blogs
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: documentation
          text: Documentation
          href: /blog/category/Documentation
          svg: "material-symbols:unknown-document-outline-rounded"
          target: _self
        - id: examples
          text: Examples
          href: /blog/category/Examples
          svg: "material-symbols:deployed-code-outline"
          target: _self
        # ã‚µãƒ–ãƒ¡ãƒ‹ãƒ¥ãƒ¼é …ç›®ã®è¨­å®š
    - id: project
      text: Project
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: Friend
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: Contact
      href: "mailto:contact.evesunmaple@outlook.com"
      target: _blank # æ–°ã—ã„ã‚¿ãƒ–ã§é–‹ã
      svg: "material-symbols:attach-email-outline-rounded"

# ãƒ¦ãƒ¼ã‚¶ãƒ¼ã®ãƒ—ãƒ­ãƒ•ã‚£ãƒ¼ãƒ«æƒ…å ±
user:
  name: EveSunMaple # ãƒ¦ãƒ¼ã‚¶ãƒ¼å
  site: "https://frosti.saroprock.com" # ãƒ¦ãƒ¼ã‚¶ãƒ¼ã®ã‚¦ã‚§ãƒ–ã‚µã‚¤ãƒˆ
  avatar: /profile.png # ãƒ¦ãƒ¼ã‚¶ãƒ¼ã‚¢ã‚¤ã‚³ãƒ³ã®ãƒ‘ã‚¹
  sidebar: # ã‚µã‚¤ãƒ‰ãƒãƒ¼ã®è¨­å®š
    social:
      - href: "https://afdian.com/a/saroprock" # ãƒªãƒ³ã‚¯
        ariaLabel: Support my work # ã‚¢ã‚¯ã‚»ã‚·ãƒ“ãƒªãƒ†ã‚£ç”¨ãƒ©ãƒ™ãƒ«
        title: Support my work # ãƒ›ãƒãƒ¼æ™‚ã®ã‚¿ã‚¤ãƒˆãƒ«
        svg: "ri:cup-line"
      - href: "https://github.com/EveSunMaple"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/438392347"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/EveSunMaple"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
  footer:
    social:
      - href: "https://afdian.com/a/saroprock" # ãƒªãƒ³ã‚¯
        ariaLabel: Support my work # ã‚¢ã‚¯ã‚»ã‚·ãƒ“ãƒªãƒ†ã‚£ç”¨ãƒ©ãƒ™ãƒ«
        title: Support my work # ãƒ›ãƒãƒ¼æ™‚ã®ã‚¿ã‚¤ãƒˆãƒ«
        svg: "ri:cup-line"
      - href: "https://github.com/EveSunMaple"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/438392347"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/EveSunMaple"
        ariaLabel: X(twitter)
        title: X(twitter)
        svg: "ri:twitter-line"
